# Empty
steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: install_frontend_dep
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: install_functions_dep
    args: ['run', 'installFunctions']
    waitFor: ['-']

  - name: 'gcr.io/$PROJECT_ID/firebase'
    entrypoint: bash
    args:
      [
        '-c',
        'firebase deploy --only functions --project $PROJECT_ID --token $$ENC_FIREBASE_TOKEN',
      ]
    secretEnv: ['ENC_FIREBASE_TOKEN']

  - name: 'gcr.io/cloud-builders/npm'
    id: gatsby_build
    args: ['run', 'build']
    env:
      [
        'GATSBY_HANDLE_APPLICATION_ENDPOINT=https://europe-west1-dps-website-244212.cloudfunctions.net/handleApplicationForm',
        'CURR_ENV=production',
      ]
    waitFor: ['install_frontend_dep']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'app',
        'deploy',
        'website-prod.app.yaml',
        '--project',
        'dps-website-244212',
        '--log-http',
        '--verbosity',
        'debug',
      ]
    waitFor: ['gatsby_build']

secrets:
  - kmsKeyName: projects/dps-website-244212/locations/global/keyRings/website-staging/cryptoKeys/website-staging-deploykey
    secretEnv:
      ENC_FIREBASE_TOKEN: CiQAV4+1gSE4EixsWcwvMmly1lHUTAFT9XNGfs1Aku2NWtTRvtYSVgANnU3aZCVWo1UX0JZQ6KH3NPnRw6zEKFE3GUr4BzGCGga+Uz8EuqxDSi7+GriRTqKtsC/tEFpAE8cwsGYhi0DrzDykRhzVc+Gtq6QhyISMQa2aegZN
