# Empty
steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: install_frontend_dep
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: install_functions_dep
    args: ['run', 'installFunctions']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/npm'
    id: gatsby_build
    args: ['run', 'build']
    env:
      [
        'GATSBY_HANDLE_APPLICATION_ENDPOINT=https://europe-west1-dps-website-244212.cloudfunctions.net/handleApplicationForm',
        'GATSBY_ENV=production',
      ]
    waitFor: ['install_frontend_dep']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'app',
        'deploy',
        'website-prod.app.yaml',
        '--project',
        '$PROJECT_ID',
        '--log-http',
        '--verbosity',
        'debug',
      ]
    waitFor: ['gatsby_build']
timeout: 900s
